### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by codingbylch** [wanniwa/transtar#2]
建议：希望能支持配置自定义的 AI域名地址

**Comment by wanniwa** [comment]
有可以用来测试的 ai 吗，我用的Python 的 openai 库实现的，不知道你说的AI域名接口会不会有区别

**Comment by codingbylch** [comment]
我使用的是API域名是：https://api.chatanywhere.tech
这个可以免费使用gpt-4o-mini一小段时间，所以想着能不能自定义配置api域名哈哈。这个是他们的接口文档：https://chatanywhere.apifox.cn/ 应该和openai官方一样的&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月19日(星期二) 上午9:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wanniwa/transtar] 功能建议 (Issue #2)














 
有可以用来测试的 ai 吗，我用的Python 的 openai 库实现的，不知道你说的AI域名接口会不会有区别

**Comment by wanniwa** [comment]
可以支持，下个版本带上

**Comment by wanniwa** [comment]
2.1.1已经发布，支持了
